name: Baidu Request

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次

jobs:
  request-baidu:
    runs-on: ubuntu-latest
    steps:
      - name: 请求百度
        run: curl -o baidu_response.html http://121.37.137.26

      - name: 上传请求结果
        uses: actions/upload-artifact@v4
        with:
          name: baidu-response
          path: baidu_response.html
